### ISSUE TITLE
Massive Lag issue with Fluid handling machines [1.18.2]

### ISSUE THREAD

**Issue by DerCommander323** [MikeTheShadow/VoluminousEnergy#100]
**Describe the bug**
After some experimenting, it seems that most tiles in this mod that process fluids (like Combustion Generator, Centrifugal Agitator or even Tooling Station) will passively use about 3mspt to check for fluids.

**To Reproduce**
1. Place a few liquid handling machines
2. Run some kind of profiler (or see /forge tps)
3. See that the machines use about 3k nanoseconds/t (3mspt) which causes a tps drop with only like 15 machines

**Expected behavior**
The machines use only a few ns/t (like other machines that do not need fluids do!)

**Screenshots**
Observable in game profiler:
![image](https://user-images.githubusercontent.com/80590706/172616190-4fa8a1dd-f2a9-4693-a913-7f0248130526.png)
![image](https://user-images.githubusercontent.com/80590706/172616992-0d5b7906-6a5b-41ba-adff-6da95e3487a3.png)

Spark profiler: https://spark.lucko.me/yYwr6sX6FS

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mod Version: VoluminousEnergy-1.18.2-0.3.0.3b
 - Forge Version: 40.1.41 (for MC 1.18.2)
 - Singleplayer

**Additional context**
This seems to happen with all machines that need fluids to work except the gas furnace for some reason and blast furnaces only if they contain valid item recipes. The combustion generator which needs 2 fluids also uses about double the ns, which further shows its fluid handling that causes this.

minecraft log: https://mclo.gs/0bfb643

**Comment by Eelt** [comment]
Hi there, 

So this is only affecting machines actively processing fluids? If they have no FE in them but have a valid fluid does it still lag?

I'd imagine the most likely culprit might be querying recipes, but this is not happening with machines that only use items?

**Comment by DerCommander323** [comment]
It happens with completely new machines, no fluids, no power and no items in them (except the blast furnace it needs items to lag)

**Comment by Eelt** [comment]
What mod/what are you using to get the overlay on the Tile/Block Entities?

**Comment by Eelt** [comment]
Closing as this should be addressed in [v1.18.2-0.3.1.1](https://github.com/MikeTheShadow/VoluminousEnergy/releases/tag/v1.18.2-0.3.1.1) for 1.18.2 users and [v1.19-0.3.0.1](https://github.com/MikeTheShadow/VoluminousEnergy/releases/tag/v1.19-0.3.0.1) for 1.19 users.
