### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zinsser901224** [MikeTheShadow/VoluminousEnergy#110]
**Describe the bug**
A clear and concise description of what the bug is. Make sure it's one bug per report.

when i click the single-play then game crashed

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS (Windows, Mac, Linux) win11
- Mod Version [1.19.2]
- Forge Version [43.2.6]
- mod version :[Voluminous Energy 1.19-0.4 Alpha 1a](https://www.curseforge.com/minecraft/mc-mods/voluminous-energy/files/4390980)

**Additional context**

[crash-2023-03-02_03.48.06-client.txt](https://github.com/MikeTheShadow/VoluminousEnergy/files/10864809/crash-2023-03-02_03.48.06-client.txt)

**Comment by Eelt** [comment]
Seems to be an issue with deserializing a Crusher recipe? Did you make custom crusher recipes or are using a mod that adds custom Crusher recipes?

There's an API break between 0.3 and 0.4 for Crusher recipes since now you can define XP amounts in the JSONs.

**Comment by MikeTheShadow** [comment]
Closed for being stale. Reopen if more information can be provided.
