### ISSUE TITLE
help me see spark about VoluminousEnergy

### ISSUE THREAD

**Issue by windy664** [MikeTheShadow/VoluminousEnergy#114]
https://spark.lucko.me/zKwuPAUXX5

![image](https://github.com/MikeTheShadow/VoluminousEnergy/assets/81475218/c3bf9be6-28d9-4f68-90da-b5b42638ee7c)

my server tps is too low .
help me!
![image](https://github.com/MikeTheShadow/VoluminousEnergy/assets/81475218/d6e93ed5-ac73-4bc6-a45e-42c2fe1da277)

**Comment by MikeTheShadow** [comment]
There is an issue with the way some tile entities access recipes. A fix is in the works which is slated for the 0.5 release. I will update this issue when it arrives.

**Comment by Eelt** [comment]
We implemented some optimizations that should address the performance issues mentioned in this bug report. Please retest on 1.20.2 0.5 builds before re-opening if the issue persists.
