### ISSUE TITLE
Spam in logs

### ISSUE THREAD

**Issue by Jerome226** [MikeTheShadow/VoluminousEnergy#21]
Voluminous Energy is spamming the logs when loaded on a server.
[spam.log](https://github.com/MikeTheShadow/VoluminousEnergy/files/6909917/spam.log)

**Comment by Eelt** [comment]
Working as intended. There's already an option in the Config file under "Feature Generation" called "Enable Logging" which you can set to false to disable.

Your log also shows Dungeon Crawl and projectvibrantjourneys doing the same thing, logging for each biome when the mod receives a BiomeLoadingEvent.

**Comment by Eelt** [comment]
I'd also like to add that this would only happen on startup when BiomeLoadingEvents happen. It would not continuously spam a server or client.
