### ISSUE TITLE
FPS Drop on Certain Machines

### ISSUE THREAD

**Issue by sjieh** [MikeTheShadow/VoluminousEnergy#23]
Completing a Distillation Unit multiblock currently drops my FPS by ~15-20%, adding more Distillation Units drops it further.
I've noticed the same behavior with the Stirling Generator, so it's possible other machines might also have this issue.

![image](https://user-images.githubusercontent.com/4664921/136055592-d6accd15-3a2e-42f3-b0c6-9e9f044b5858.png)
![image](https://user-images.githubusercontent.com/4664921/136055603-7fbd00aa-d081-44d6-9a96-cc854afa488d.png)
![image](https://user-images.githubusercontent.com/4664921/136057353-18e07491-5034-44fe-8344-eadf0fb3ced0.png)

**Comment by MikeTheShadow** [comment]
this appears fixed in later versions. Please update us if this is not the case.

**Comment by MikeTheShadow** [comment]
Closed due to inactivity.
