### ISSUE TITLE
Issues with the Distillation Unit

### ISSUE THREAD

**Issue by sjieh** [MikeTheShadow/VoluminousEnergy#24]
1. Even though the recipes exist in JEI, the Distillation Unit does not let me input Crude Oil from either Thermal Series and PneumaticCraft into the Distillation Unit. I have tried inputting a bucket in the GUI, and through pipes from Mekanism and Pipez, but neither work. Only Crude Oil from VE works, both from buckets and pipes.

2. The I/O seems to be very buggy. Even with output set correctly, the machine does not output fluids into other tanks. I have tried pipes from Mekanism and Pipez, and placing tanks from various mods next to the machine.
![image](https://user-images.githubusercontent.com/4664921/136058967-963a0bca-72b4-4995-8a91-6b2a6de15065.png)
![image](https://user-images.githubusercontent.com/4664921/136059218-4232f02d-ea01-4470-aa10-5d4604efb648.png)

**Comment by MikeTheShadow** [comment]
Pipes are now working with #55 on the latest branch. No plans for direct fluid->machine transfer anytime soon.
