### ISSUE TITLE
Setting all slots to go down, doesn't let pipes pull all of the slots.

### ISSUE THREAD

**Issue by ProsperCraft** [MikeTheShadow/VoluminousEnergy#28]
![image](https://user-images.githubusercontent.com/4427684/139557423-38a50862-d749-491c-ab7c-1ed50c6380c2.png)

**Comment by Eelt** [comment]
The current architecture only allows one capability per side, which means that only the first slot (in the code) bounded to that side will be used.

With VE's current design for this, it is working as intended.
