### ISSUE TITLE
[1.17.1] Copper dust doesn't have any recipe.

### ISSUE THREAD

**Issue by ProsperCraft** [MikeTheShadow/VoluminousEnergy#30]
You can't smelt it to ingots or use it for anything.

**Comment by Eelt** [comment]
Woops, looks like when I added Copper Dust in Alpha 2 I forgot to add the
smelting recipe for Copper Dust into Copper Ingots.

Additionally, the tags for Copper Dust are also missing, so even if other
mods add a smelting recipe for anything tagged as Copper Dust, it wouldn't
apply to VE's Copper Dust as it's not tagged as Copper Dust.

I'll get around to fixing this later this week or on the weekend when I
have time and publish a new build with the fix.

**Comment by Eelt** [comment]
Should now be fixed in Voluminous Energy 1.17.1-0.2 Alpha 4
