### ISSUE TITLE
Added Bamboo to stirling, seems to have broken

### ISSUE THREAD

**Issue by poboy975** [MikeTheShadow/VoluminousEnergy#34]
I'm on Minecraft 1.18
Voluminous Energy ver.1.18-0.2-alpha 1c

I added a couple of recipes using kubeJS. Most worked great. Example, I added a cobble to gravel and gravel to sand for the crusher. That worked just fine. I have a large bamboo farm, and I noticed that bamboo wouldn't burn in the stirling generator. So I added a recipe for that. It worked great, at first. when it finished burning the first bamboo rod, the status shows 100%, no ticks left. But the number of bamboo in the machine didn't decrease and start on the next one. Now, even removing the bamboo, picking up and replacing the generator doesn't fix it. 
This is the recipe I added:
e.custom({
  "type": "voluminousenergy:stirling",
  "ingredient": {
    "item": "minecraft:bamboo",
    "count": 1
  },
  "process_time": 1600,
  "energy_per_tick": 128
}
)

**Comment by Eelt** [comment]
I haven't tested with KubeJS yet, but I copy-pasted your recipe into a JSON that would normally be integrated into the main jar in my dev environment. 

The recipe works fine with bamboo, the `percent burned` does reach 100% when the bamboo is completely burned, but the `ticks left` show zero, and the generation rate turns to zero and no more power is generated. Leaving bamboo in the Stirling generator causes it to burn the next one without issue (just like coal, coal coke, etc (all the ones that come built-in)). 

Try using coal and see if you're having the same issue, it might be a KubeJS issue, or something going on with interaction between VE and KubeJS, but I'll have to test that later.
