### ISSUE TITLE
Electric Furnace high energy usage

### ISSUE THREAD

**Issue by poboy975** [MikeTheShadow/VoluminousEnergy#35]
I'm on Minecraft 1.18
Voluminous Energy ver.1.18-0.2-alpha 1c

Not sure if this is a bug or working as intended. The electric furnace seems to use a very large amount of power compared to other machines that I've tried so far. I can run two crushers at the same time, with three stirling generator using a stack of coal each with no problems on power draw. Even with 3 quartz multipliers in each. If I use 1 electric furnace with just 1 quartz multiplier its sucks all the power out and bottoms out everything. Is this working as intended? I seems like I'd need 100's of stirling gens to power the electric furnace with 4 quartz multipliers, though I haven't tested just how many I would need.

**Comment by Eelt** [comment]
By default, the Electric Furnace should use 64 FE/t. Double-check your config file (`voluminousenergy-common.toml` under the `config` folder) that the field `Power Consumption` under the Electric Furnace section isn't overwritten.

The curve should be 0 --> 64, 1 --> 128, 2 --> 256, 3 --> 512, 4 --> 1024

1024 would be 8 Stirling Generators if you have 4 Quartz Multipliers in them, or 1 Combustion Generator with Nitroglycerin + Dinitrogen Tetroxide (936 FE/t) with a little extra help from something else (need 88 FE/t more, 1 Stirling Generator could fit the bill). 

I'm seeing this setup 1x Electric Furnace with 4 QMs, with 1x Combustion Generator @ 936 FE/t and 1x Stirling Generator @ 128 FE/t working perfectly fine with a maxed out Electric Furnace. So, I'd double check your config file that the 64 value isn't set to something higher.

**Comment by poboy975** [comment]
Ok, sorry for the delay. I've just checked, it's at 64. So I just need to improve my power generation, by either adding more stirling gens, or upgrading to combustion gen. Thanks!
