### ISSUE TITLE
Integration with Refined Storage does not fully empty the Crusher output slots

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#40]
MC Version: 1.18.1

Mod Version: 1.18-exp code set

Issue: When using the Importer from the Refined Storage mod only the Output slot is emptied.  The RNG slot (secondary output) does not get emptied.

**Comment by MikeTheShadow** [comment]
Working on a fix to be tested in branch [1.18-exp-output-fix](https://github.com/MikeTheShadow/VoluminousEnergy/tree/1.18-exp-output-fix)

**Comment by jack-flash** [comment]
I have a code fix for this...I will issue a pull request shortly...give me a few ins to sort thru a mess I just made.

**Comment by jack-flash** [comment]
This will need to be added to most of your other blocks too, I think.

**Comment by MikeTheShadow** [comment]
I'm working on a broader fix for it right now. I will review the changes you've made and if yours is better yours will be merged.

**Comment by MikeTheShadow** [comment]
Fixed with PR #55
