### ISSUE TITLE
When FE runs out mid processing, the processing gets completely reset, rather than just pausing

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#43]
MC: 1.18.1

If the FE runs out, for example in the Electrolyzer, the processing is completely lost instead of just pausing until enough energy is built up to process a bit more.

**Comment by Eelt** [comment]
When there's no power, machines will call a new method that will eventually result in the counter back to the original length value. The rate of which the counter is incremented will be configurable in the `voluminousenergy-common.toml` file.
