### ISSUE TITLE
Refining Rutile dust in the Electrolyzer gets stuck if you don't remove the bucket of Oxygen

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#44]
MC: 1.18.1

It only processes once until you remove the bucket of oxygen

**Comment by jack-flash** [comment]
Guessing this is because the buckets of oxygen will not stack?

**Comment by Eelt** [comment]
The bucket has a max stack size of 1, this is true for vanilla fluids as well. 
Since the bucket size has a max stack size of one this is working as intended.

**Comment by jack-flash** [comment]
This makes the block hard to "fire and  forget" and limits its use with automation as you have to manage the Electrolyzer one item at a time.

**Comment by Eelt** [comment]
For the time being, map each output slot you need to a different side and have multiple pipes/extractors connecting to those sides. @MikeTheShadow is working on enhancing the IO/Capability system to add support for multiple slots mapped to a single side.

**Comment by Eelt** [comment]
Alternatively, use a mod like Xnet that can extract from multiple sides using a single connector if you don't want to use a bunch of pipes on different sides.
