### ISSUE TITLE
The VE Blast Furnace shows the right FE reading in The One Probe, but the bar is not correct in the GUI

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#45]
MC: 1.18.1

The reading in the GUI is bouncing all over the place and does not show the red bar at all, whereas TOP shows the steadily increasing amount of FE being stored.

**Comment by jack-flash** [comment]
Once fully charged, the bar is still not showing any red, but the FE reading shows a full charge.

**Comment by MikeTheShadow** [comment]
Fixed with PR #62
