### ISSUE TITLE
VE Blast Furnace does not seem to be showing the recipes for the standard Blast Furnace

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#46]
MC 1.18.1

Additionally, when you click on the arrow to show the recipes from the Blast Furnace GUI, it shows "Industrial Furnace" and no recipes at all.

**Comment by jack-flash** [comment]
It does not even take the VE Iron dust, it seems.  So it appears all of the recipes are not registered correctly.

**Comment by jack-flash** [comment]
It appears to allow you to store a bucket of oxygen in the top left, but cannot get it to accept anything else

**Comment by Eelt** [comment]
The Voluminous Energy blast furnace is not equivalent to the Vanilla Blast Furnace. Maybe the translation should be updated to make this more clear, but if you need analogous examples, look at the Industrial Blast Furnace from Tech Reborn/GregTech, Arc Furnace from Immersive Engineering, etc.

The Blast Furnace, if you complete the multiblock, should accept recipes from the Industrial Blasting recipe. As far as I can tell, the Blast Furnace does work with Industrial Blasting recipes so long as you include an appropriate heat source (which is also listed in JEI).

**Comment by jack-flash** [comment]
Ok, the name intuitively makes me think it is a Forge Energy version of the vanilla Blast Furnace.  So no compatibility with the vanilla Blast Furnace.  Gotcha.
