### ISSUE TITLE
Centrifugal Agitator recipes are not showing when clicking the arrow in the GUI

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#47]
MC: 1.18.1

I can get the Oxygen to load from a bucket of oxygen.

**Comment by Eelt** [comment]
The coordinates are wrong, the clickable recipe area is up and right to the progress arrow

**Comment by jack-flash** [comment]
I see them now..gotcha!

**Comment by MikeTheShadow** [comment]
It should be fixed. Re-open if not.
