### ISSUE TITLE
Distillation Unit not functioning correctly

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#48]
MC: 1.18.1

The power bar is not showing red when charging or charged.  The ID button does not show the Input/Output options.  A Beyond Earth Oil Bucket can be place in the input, but it does not unload the oil into the block for processing.

**Comment by MikeTheShadow** [comment]
This is a multiblock issue. Will be updated in 0.3 you need to build the multiblock first. We'll move the warning more center so that it's' easier to see and causes less confusion

**Comment by MikeTheShadow** [comment]
Fixed with PR #55 make sure multiblock is built as well
