### ISSUE TITLE
VE Blast Furnace Tank Input, does not seem to accept fluid inputs

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#51]
MC: 1.18.1

If I try to feed Fluids in with the Refined Storage mod, the Blast Furnace does not appear to accept fluid inputs.

**Comment by MikeTheShadow** [comment]
Make sure you've built the multiblock when testing

**Comment by Eelt** [comment]
Appears to work fine when assembling the multiblock.
