### ISSUE TITLE
VE Electric Furnace does not allow you to click on the GUI arrow to see all recipes possible

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#52]
MC: 1.18.1

**Comment by Eelt** [comment]
The Electric Furnace uses Vanilla Furnace and Blasting recipes, I don't see the need to have the progress bar open the JEI menu in lieu of showing the progress.

**Comment by jack-flash** [comment]
Just pointing out consistency issues across the blocks.  Some of your blocks show the recipes, and some don't.  Your call.

**Comment by jack-flash** [comment]
A parallel is the Create mod's Crusher, which opens up to hundreds of recipes..
