### ISSUE TITLE
VE Electric Furnace eats a gold ore block per processing tick it seems

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#53]
MC: 1.18.1

If you place a stack of gold blocks in the VE EF, each tick in the processing seems to remove a block, which should not happen if it is still processing.

**Comment by Eelt** [comment]
![image](https://user-images.githubusercontent.com/6241870/149820452-26deea55-278e-48c0-93ee-daebeae22c2d.png)
![image](https://user-images.githubusercontent.com/6241870/149820531-40db353b-7e04-448f-8243-5c0cf7187e34.png)

Can't reproduce, seems to be working fine for me in the standard development environment.

**Comment by jack-flash** [comment]
Ah, in my haste turns out this is related to the ID Slot 0 pointing up and allowing ItemExtraction from the Input Slot, which is not what I would have expected.  So the Output AND Input slots seem to allow both itemInsert and ItenExtract functionality.
