### ISSUE TITLE
VE Aqueoulizer does not seem to import or export fluids

### ISSUE THREAD

**Issue by jack-flash** [MikeTheShadow/VoluminousEnergy#54]
MC: 1.18.1

With the Aqueoulizer it seems to not function with fluids.  Tried to export the final out put of the fluids and it does not work.  As well, if I put an empty bucket in the right most side, it does not seem to fill the bucket with the resulting product.

When I tried to import water for the recipe, I could only get it into the block using a bucket.

**Comment by MikeTheShadow** [comment]
Will be fixed with the [1.18 output fix](https://github.com/MikeTheShadow/VoluminousEnergy/tree/1.18-exp-output-fix)
