### ISSUE TITLE
Unable to connect cables in beta1 1.18.1

### ISSUE THREAD

**Issue by aAndrew3030** [MikeTheShadow/VoluminousEnergy#65]
Trying to connect refined storage cables to the sawmill caused my world to crash and unable to load (I had to delete the chunk). Other machines are unable to connect to fluid pipes of any kind.

version .3 beta 1
forge .66

[crash-2022-02-04_21.27.03-server.txt](https://github.com/MikeTheShadow/VoluminousEnergy/files/8008942/crash-2022-02-04_21.27.03-server.txt)

**Comment by MikeTheShadow** [comment]
Fixed in the latest hotfix .3 Beta 1A. Please provide the specific blocks that do not work with fluid pipes. We are unable to find any issues related to fluid IO. Make sure you've set the specific output slot location to the exact side you've placed the pipe as well.
