### ISSUE TITLE
wrong pattern encoding on Refined Storage when move items in JEI

### ISSUE THREAD

**Issue by gisellevonbingen** [MikeTheShadow/VoluminousEnergy#71]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44163945/156033746-0ab14be8-7659-4493-8ea3-509bad5ce876.png)
![image](https://user-images.githubusercontent.com/44163945/156033753-19259f2d-5740-4f9a-9f0e-67560c66ab97.png)

i guess coal dust and water have to move to input grid (left)

https://github.com/MikeTheShadow/VoluminousEnergy/blob/12da69fec6b1a6db8c5a412ca778a48b1f7fa10e/src/main/java/com/veteam/voluminousenergy/compat/jei/AqueoulizingCategory.java#L106-L108

i found cause from JEI Category code
ingredients are need be set as input (via set 'input' argument)
like this
```java
itemStacks.init(0, true, 2, 10);
fluidStacks.init(1, true, 25, 11);
fluidStacks.init(2, false, 73,11);
```

it seem all of category has same problem

**Comment by Eelt** [comment]
Should be fixed in PR #74
